# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 36.0.1

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.18-4
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
      #- ssldata:/usr/local/apache2/conf/certs
      - ~/.ssh/:/var/www/.ssh/
      - ~/.composer:/var/www/html/var/composer_home # Magento 2 does dumb shit with sampledata:deploy command
    extra_hosts:
     - "host.docker.internal:172.17.0.1"
    environment:
      PHP_IDE_CONFIG: "serverName=magento2.test"

  phpfpm:
    # image: markoshust/magento-php:7.4-fpm-3
    build: ../images/php/8.1
    environment:
      PHP_IDE_CONFIG: "serverName=magento2.test"
    links:
      - db
    volumes: *appvolumes
    extra_hosts:
     - "host.docker.internal:172.17.0.1"

  db:
    image: percona:5.7
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: markoshust/magento-elasticsearch:7.7.1-0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  # Disabling cron by default as it uses higher CPU, enable if needed
  cron:
    # image: markoshust/magento-php:7.4-fpm-3
    build: ../images/php/8.1
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
